#!/bin/bash
CUDA_VISIBLE_DEVICES=0 python main.py \
    --model vim_tiny_patch16_stride8_224_bimambav2_final_pool_mean_abs_pos_embed_with_midclstok_div2 \
    --batch-size 32 \
    --lr 1e-4 \
    --min-lr 1e-6 \
    --warmup-lr 1e-4 \
    --drop-path 0.0 \
    --weight-decay 1e-4 \
    --early-stopping \
    --early-stopping-patience 5 \
    --early-stopping-delta 0.0 \
    --is-binary True \
    --sched plateau \
    --num_workers 4 \
    --data-set CANCER \
    --data-path  /home/T2410196/VisionMamba/CANCER \
    --output_dir ./output/CANCER/vim_tiny_patch16_stride8_224_bimambav2_final_pool_mean_abs_pos_embed_with_midclstok_div2 \
    --epochs 50 \
    --finetune /home/T2410196/VisionMamba/Vim-tiny-midclstok/vim_tiny_73p1.pth \
    --no_amp